/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import logica.dataConnection;

/**
 *
 * @author user
 */
public class VentanaEliminarEstudiante extends javax.swing.JFrame {

      // atributos para el manejo de la base de datos
    PreparedStatement pst;
    Connection cn;
    ResultSet result;
    /**
     * Creates new form VentanaEliminarEstudiante
     */
    public VentanaEliminarEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelTexto = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jTextFieldDocumento = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Elinimar Estudiante");
        setIconImage(getIconImage());
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Eliminar Estudiantes");

        jLabelTexto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelTexto.setText("<html>Para eliminar un estudiante, debe buscar el estudiante por <br> el número de Documento de Identidad</html>");

        jLabelDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelDocumento.setText("Documento C.C/T.I:");

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar Estudiante");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabelTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDocumento)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDocumento)
                    .addComponent(jTextFieldDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonEliminar)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        int seleccion=JOptionPane.showConfirmDialog(null, "Seguro que quiere eliminar el estudinate","CONFIRMAR",JOptionPane.QUESTION_MESSAGE);
        if(seleccion==JOptionPane.YES_OPTION){
        int documento = Integer.parseInt(jTextFieldDocumento.getText());
			cn = dataConnection.conexion();
			try {
				pst = cn.prepareStatement("delete from estudiante where documento=?");
				pst.setInt(1, documento);
				int res = pst.executeUpdate();
				if (res > 0) {
					JOptionPane.showMessageDialog(null, "Estudiante eliminado satisfractoriamente");
					limpiar();
				} else {
					JOptionPane.showMessageDialog(null, "el estudiante no existe");
					limpiar();
				}
				cn.close();

			} catch (SQLException e1) {
				e1.printStackTrace();
			}
        }else if(seleccion==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "El estudiante no se elimino.");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("imagenes/Escudo.png"));


        return retValue;
    }
    public void limpiar() {
		jTextFieldDocumento.setText(" ");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldDocumento;
    // End of variables declaration//GEN-END:variables
}
