/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author user
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarOpcionsAdmin = new javax.swing.JToolBar();
        jButtonCrearEstudiante = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonBuscarEstudiante = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonModificarEstudiante = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButtonEliminarEstudiante = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButtonModificarDatos = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("VentanaAdministrador"); // NOI18N
        setResizable(false);

        jToolBarOpcionsAdmin.setRollover(true);

        jButtonCrearEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonCrearEstudiante.setText("Crear Estudiante");
        jButtonCrearEstudiante.setFocusable(false);
        jButtonCrearEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCrearEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCrearEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEstudianteActionPerformed(evt);
            }
        });
        jToolBarOpcionsAdmin.add(jButtonCrearEstudiante);
        jToolBarOpcionsAdmin.add(jSeparator2);

        jButtonBuscarEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonBuscarEstudiante.setText("Buscar Estudiante");
        jButtonBuscarEstudiante.setFocusable(false);
        jButtonBuscarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonBuscarEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEstudianteActionPerformed(evt);
            }
        });
        jToolBarOpcionsAdmin.add(jButtonBuscarEstudiante);
        jToolBarOpcionsAdmin.add(jSeparator3);

        jButtonModificarEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModificarEstudiante.setText("Modificar Estudiante");
        jButtonModificarEstudiante.setFocusable(false);
        jButtonModificarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarOpcionsAdmin.add(jButtonModificarEstudiante);
        jToolBarOpcionsAdmin.add(jSeparator4);

        jButtonEliminarEstudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonEliminarEstudiante.setText("Eliminar Estudiante");
        jButtonEliminarEstudiante.setFocusable(false);
        jButtonEliminarEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEstudianteActionPerformed(evt);
            }
        });
        jToolBarOpcionsAdmin.add(jButtonEliminarEstudiante);
        jToolBarOpcionsAdmin.add(jSeparator5);

        jButtonModificarDatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonModificarDatos.setText("Modificar Datos");
        jButtonModificarDatos.setFocusable(false);
        jButtonModificarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonModificarDatos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDatosActionPerformed(evt);
            }
        });
        jToolBarOpcionsAdmin.add(jButtonModificarDatos);
        jToolBarOpcionsAdmin.add(jSeparator6);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Generar Informe");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBarOpcionsAdmin.add(jButton1);
        jToolBarOpcionsAdmin.add(jSeparator1);

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setFocusable(false);
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarOpcionsAdmin.add(jButtonSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarOpcionsAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarOpcionsAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEstudianteActionPerformed
        // TODO add your handling code here:
        VentanaBuscarEstudiante ventana= new VentanaBuscarEstudiante();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonBuscarEstudianteActionPerformed

    private void jButtonCrearEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEstudianteActionPerformed
        // TODO add your handling code here:
        VentanaCrearEstudiante ventana= new VentanaCrearEstudiante();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonCrearEstudianteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaGenerarInforme ventana= new VentanaGenerarInforme();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDatosActionPerformed
        // TODO add your handling code here:
        VentanaModificarDatosAdmin ventana= new VentanaModificarDatosAdmin();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonModificarDatosActionPerformed

    private void jButtonEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEstudianteActionPerformed
        // TODO add your handling code here:
        VentanaEliminarEstudiante ventana= new VentanaEliminarEstudiante();
        ventana.setVisible(true);
    }//GEN-LAST:event_jButtonEliminarEstudianteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarEstudiante;
    private javax.swing.JButton jButtonCrearEstudiante;
    private javax.swing.JButton jButtonEliminarEstudiante;
    private javax.swing.JButton jButtonModificarDatos;
    private javax.swing.JButton jButtonModificarEstudiante;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBarOpcionsAdmin;
    // End of variables declaration//GEN-END:variables
}
